### ISSUE TITLE
Error using '/bin/tar' in my container

### ISSUE THREAD

**Issue by BLKKKBVSIK** [subosito/flutter-action#18] opened 2019-11-24 17:42 UTC
Hello,

I'm trying to set up my first Github Action, and im getting an error using your flutter-action:
I ll attach log to the issue.

Here is my actual dart.yml
```name: Dart CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Flutter action
        uses: subosito/flutter-action@v1.1.1
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk
```

And i got an error about the `/bin/tar` of the container

```Run subosito/flutter-action@v1
/usr/bin/docker exec  5b59092a4ed8fd5c8f78f3a026cccaf960b4dc3145c3ea07a0a9b34a170e6eb3 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
/bin/tar x -C /__w/_temp/temp_401169546 -f /__w/_temp/b11cab69-922a-4229-b27e-57f05f10e955
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
##[error]The process '/bin/tar' failed with exit code 2
##[error]Node run failed with exit code 1
```

So here is my log archive:
[logs_4.zip](https://github.com/subosito/flutter-action/files/3883930/logs_4.zip)

**Comment by BLKKKBVSIK** [comment] 2019-11-25 11:55
I actually didn't saw that its the same problem as issue #17
Sorry for the duplicate, tho i got the complete log file, so i ll keep it open in case it can help you.

**Comment by subosito** [comment] 2019-11-30 01:54
Duplicate of #5. See solution https://github.com/subosito/flutter-action/issues/5#issuecomment-529193339.

**Closed by subosito** 2019-11-30 01:54 UTC
