### ISSUE TITLE
Error using dev channel

### ISSUE THREAD

**Issue by Fernandomr88** [subosito/flutter-action#17] opened 2019-11-23 19:56 UTC
My code

 ```
name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest


    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
```

Output:
```
 Run subosito/flutter-action@v15s
##[error]Node run failed with exit code 1
Run subosito/flutter-action@v1
/usr/bin/docker exec  b88ae8e182610cd8a1da6822d4fabc7b15544e1957c9630acdbe6fab4b6bf2ce sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
/bin/tar x -C /__w/_temp/temp_457657794 -f /__w/_temp/6da63d29-5d2f-421d-83f6-a4942147e494
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
##[error]The process '/bin/tar' failed with exit code 2
##[error]Node run failed with exit code 1
```

**Comment by subosito** [comment] 2019-11-30 01:55
Duplicate of #5

**Comment by subosito** [comment] 2019-11-30 01:55
See solution https://github.com/subosito/flutter-action/issues/5#issuecomment-529193339.

**Closed by subosito** 2019-11-30 01:55 UTC
