### ISSUE TITLE
GitHub has deprecated "set-output" as a way of passing output in actions.

### ISSUE THREAD

**Issue by jpeiffer** [subosito/flutter-action#193] opened 2022-10-12 20:18 UTC
From build output that uses this command:

<blockquote>The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/</blockquote>

**Comment by subosito** [comment] 2022-10-12 23:36
Duplicate of #192

**Closed by subosito** 2022-10-12 23:36 UTC
